import { useRef } from "react";
import Head from "next/head";
import Image from "next/image";
import Hero from "../components/Hero";
import Navbar from "../components/Navbar";
import Sidebar from "../components/Sidebar";
import About from "../components/About";

export default function Home() {
	const heroRef = useRef(null);
	const aboutRef = useRef(null);

	return (
		<div>
			<Head>
				<title>Jimmy Zhang</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/assets/favicon.ico" />
			</Head>

			<Navbar />

			<Sidebar hero={heroRef} about={aboutRef} />

			<Hero ref={heroRef} />

			<About ref={aboutRef} />
		</div>
	);
}
