import Head from "next/head";
import Image from "next/image";
import Hero from "../components/Hero";
import Navbar from "../components/Navbar";

export default function Home() {
	return (
		<div>
			<Head>
				<title>Jimmy Zhang</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/assets/favicon.ico" />
			</Head>

			<Navbar />

			<Hero />
		</div>
	);
}
