import { useRef } from "react";
import Head from "next/head";
import Image from "next/image";
import Hero from "../components/Hero";
import Navbar from "../components/Navbar";
import Sidebar from "../components/Sidebar";
import About from "../components/About";
import Projects from "../components/Projects";
import Contact from "../components/Contact";

export default function Home() {
	const heroRef = useRef(null);
	const aboutRef = useRef(null);
	const projectsRef = useRef(null);
	const contactRef = useRef(null);

	return (
		<div>
			<Head>
				<title>Jimmy Zhang</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/assets/favicon.ico" />
			</Head>

			<Navbar />

			<Sidebar
				hero={heroRef}
				about={aboutRef}
				projects={projectsRef}
				contact={contactRef}
			/>

			<Hero ref={heroRef} />

			<About ref={aboutRef} />

			<Projects ref={projectsRef} />

			<Contact ref={contactRef} />
		</div>
	);
}
